update:
  .xo-config.json:
    route:
      json:
        compose:
          ignores: listConcat
          overrides: listConcat
          plugins: listConcat
          rules: [mapConcat, mapSort]
          $$default: overwrite
