$schema: https://raw.githubusercontent.com/zokugun/artifact/v0.6.0/schemas/v1/package.json

update:
  .xo-config.json:
    route:
      json:
        compose:
          ignores: listConcat
          overrides: listConcat
          plugins: listConcat
          rules: [mapConcat, mapSort]
          $$default: overwrite
