$schema: https://raw.githubusercontent.com/zokugun/artifact/v0.9.0/schemas/v2/package.json

journeys:
  - name: xo
    travels:
      - path: .xo-config.json
    route:
      mapSort:
        compose:
          ignores: listConcat
          overrides: listConcat
          plugins: listConcat
          rules:
            - mapConcat
            - mapSort
          $$default: overwrite
