$schema: https://raw.githubusercontent.com/zokugun/artifact/v0.11.0/schemas/v3/package.json

upsert:
  .github/**/*.yml:
    if_exists: overwrite

  .github/scripts/get-changelog.js:
    rename: .github/scripts/get-changelog.cjs

update:
  CHANGELOG.md:
    if_exists: skip

  # package.json:
  #   transforms:
  #     - description: Remove release-it from overrides
  #       jq: 'del(.overrides["release-it"])'
