name: Publish Extension
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.TOKEN_OPENVSX }}
          skipDuplicate: true
        if: env.PUBLISH_OPENVSX == 'yes'
      - name: Publish to Visual Studio Code Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.TOKEN_VSCODE }}
          registryUrl: https://marketplace.visualstudio.com
          skipDuplicate: true
        if: env.PUBLISH_VSCODE == 'yes'
