update:
  CHANGELOG.md:
    update: false
  package.json:
    filter:
      - main
      - scripts
      - devDependencies
  .github/**/*.yml:
    overwrite: true
  src/document-manager.ts:
    overwrite: true
  src/extension.ts:
    missing: false
    update: false
  src/commands/*:
    missing: false
    update: false
  src/utils/*:
    overwrite: true
