$schema: https://raw.githubusercontent.com/zokugun/artifact/v0.6.0/schemas/v1/package.json

upsert:
  "*.md":
    if_exists: overwrite

  .github/**/*.yml:
    if_exists: overwrite

  .github/workflows/close-invalid-issue.yml:
    rename: .github/workflows/mod-close-invalid-issue.yml

update:
  .github/repo-starter-kit.yml:
    if_exists: skip

variables:
  DISCUSSION_ID: 2
  ISSUE_ID: 1
  REPOSITORY_SLUG: =package.json.repository.url.split('/').slice(-2).join('/').replace('.git', '')
