update:
  test/*.ts:
    missing: false
    update: false

uninstall:
  .mocharc.yml:
    remove: true
  .test:
    remove: true
  .vscode/settings.json:
    unmerge: true
  .xo-config.json:
    unmerge: true
  package.json:
    unmerge: true
