$schema: https://raw.githubusercontent.com/zokugun/artifact/v0.6.0/schemas/v1/package.json

upsert:
  .github/**/*.yml:
    if_exists: overwrite

  .github/workflows/check-pr.yml:
    rename: .github/workflows/ci-pr.yml

  .github/workflows/lock-closed-threads.yml:
    rename: .github/workflows/mod-lock-closed-threads.yml

  .github/workflows/stale-issue-pr.yml:
    rename: .github/workflows/mod-stale-issue-pr.yml

  .lintstagedrc:
    if_exists: remove

update:
  package.json:
    filter:
      - scripts
      - devDependencies
