$schema: https://raw.githubusercontent.com/zokugun/artifact/v0.6.0/schemas/v1/package.json

update:
  '*':
    if_exists: skip

  .github/FUNDING.yml:
    if_exists: merge

variables:
  REPOSITORY_NAME: =package.json.repository.url |> toGitUrl |> _.name
  REPOSITORY_OWNER: =package.json.repository.url |> toGitUrl |> _.owner
  REPOSITORY_SLUG: =package.json.repository.url |> toGitUrl |> _.full_name
